<?php /*$this->load->view('user/popupSpecial/loykrathogDay.php');*/ ?>
<?php /*$this->load->view('user/popupSpecial/skj-establish.php');*/ ?>
<?php /*$this->load->view('user/popupSpecial/skj-welcome.php');*/ ?>
<?php /*$this->load->view('user/popupSpecial/skj-cricket.php');*/ ?>
<?php /*$this->load->view('user/popupSpecial/skj-Election2563.php');*/ ?>
<?php /*$this->load->view('user/popupSpecial/snowy.php');*/ ?>
<?php $this->load->view('user/popupSpecial/skj-learning-online.php'); ?>
<?php $this->load->view('user/popupSpecial/skj-covid19.php'); ?>
<?php $this->load->view('user/popupSpecial/skj-registerStudent.php'); ?>